name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  cupertino_icons: ^1.0.4
  flutter_webview_plugin: ^0.4.0
  flutter_cache_manager: ^3.3.0
  palette_generator: ^0.3.2
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  http: ^0.13.5
  webview_flutter: ^3.0.0
  video_player: ^2.2.17
  path_provider: ^2.0.2
  shared_preferences: ^2.0.20
  flutter_swiper: ^1.1.6
  image_picker: ^0.8.7+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - imgs/
    - mock/